sources:
  - name: "Knesset Ethics Decisions"
    description: "Decisions of the Knesset Ethics Committee, 2010-2024"
    file_pattern: "ethics_decisions/*.pdf"
    unique_id_field: "source_url"
    metadata:
      source_url: "{pdf_url}"
      download_date: "{download_date}"
    fields:
      - name: "source_url"
        description: "Direct URL to the PDF file"
        example: "https://knesset.gov.il/ethics/decisions/ethics_decision_2023_01.pdf"
      - name: "decision_date"
        description: "Date of the ethics decision"
        example: "2023-05-12"
        hint: "Look for dates in the document header"
      - name: "case_number"
        description: "Case or file number"
        example: "1234/2023"
      - name: "member_name"
        description: "Name of the Knesset member"
        example: "יוסי כהן"
      - name: "decision_text"
        description: "Full text of the decision"
        hint: "Extract the main body of the document"
      - name: "full_text"
        description: "Full content of the document"
        hint: "Always include the entire text of the document as extracted, in Hebrew."
        example: "..."
    extraction_instructions: |
      הפק את השדות הנדרשים מהטקסט של קובץ ה-PDF. השתמש ברשימת השדות וההנחיות. החזר אובייקט JSON שבו שמות השדות באנגלית, אך כל הערכים בשפה המקורית (עברית) כפי שמופיעים במסמך. אל תתרגם או תשנה את הטקסט המקורי. ודא ששדה full_text תמיד מכיל את כל הטקסט של המסמך כפי שהופק מה-PDF.

  - name: "Knesset Legal Advisor Documents"
    description: "Guidelines, legal opinions, and letters from the Legal Advisor to the Knesset"
    file_pattern: "legal_advisor_docs/*.pdf"
    unique_id_field: "source_url"
    metadata:
      source_url: "{pdf_url}"
      download_date: "{download_date}"
    fields:
      - name: "source_url"
        description: "Direct URL to the PDF file"
        example: "https://main.knesset.gov.il/Docs/legal_advisor/2024-06-15_guideline.pdf"
      - name: "document_type"
        description: "Type of the document (e.g., הנחיה, חוות דעת, מכתב)"
        example: "חוות דעת"
      - name: "title"
        description: "Title or subject of the document"
        example: "הנחיה בעניין ניגוד עניינים"
      - name: "date"
        description: "Date of the document"
        example: "2024-06-15"
      - name: "author"
        description: "Author of the document (usually היועצת המשפטית לכנסת)"
        example: "עו\"ד שגית אפיק, היועצת המשפטית לכנסת"
      - name: "recipient"
        description: "Recipient or addressee (for letters, if available)"
        example: "יו\"ר ועדת הכנסת"
      - name: "reference_number"
        description: "Internal reference or file number (if present)"
        example: "1234/2024"
      - name: "summary"
        description: "Short summary or abstract (if available)"
        example: "הנחיה זו עוסקת בניגוד עניינים של חברי הכנסת."
      - name: "full_text"
        description: "Full content of the document"
        hint: "Always include the entire text of the document as extracted, in Hebrew."
        example: "..."
    extraction_instructions: |
      הפק את השדות הנדרשים מהטקסט של קובץ ה-PDF. השתמש ברשימת השדות וההנחיות. החזר אובייקט JSON שבו שמות השדות באנגלית, אך כל הערכים בשפה המקורית (עברית) כפי שמופיעים במסמך. אל תתרגם או תשנה את הטקסט המקורי. ודא ששדה full_text תמיד מכיל את כל הטקסט של המסמך כפי שהופק מה-PDF. 