slug: unified
name: בוט מאוחד - תקנון ותקציב
description: עונה על שאלות מתוך תקנון הכנסת וחוקים נלווים וכן על שאלות בנושאי תקציב המדינה, הכנסות המדינה, התקשרויות ותמיכות תקציביות
instructions: agent.txt
tools:
  - code-interpreter
  - budgetkey
context:
  - slug: budgetkey__common_knowledge
    name: ידע רלוונטי על התקציב
    type: split
    source: common-knowledge.md
    max_num_results: 7

  - slug: takanon__common_knowledge
    name: ידע רלוונטי על התקנון
    max_num_results: 7
    sources:
    - type: google-spreadsheet
      source: https://docs.google.com/spreadsheets/d/1fEgiCLNMQQZqBgQFlkABXgke8I2kI1i1XUvj8Yba9Ow/edit?gid=0#gid=0
    - type: google-spreadsheet
      source: https://docs.google.com/spreadsheets/d/1fEgiCLNMQQZqBgQFlkABXgke8I2kI1i1XUvj8Yba9Ow/edit?gid=656974237#gid=656974237
    - type: split
      source: ../takanon/extraction/כללי אתיקה לחברי הכנסת_structure_content.json
    - type: split
      source: ../takanon/extraction/חוק הפרשנות_structure_content.json

  - slug: takanon__legal_text
    name: Knesset Bylaws (תקנון הכנסת) and related laws
    sources:
      - type: split
        source: ../takanon/extraction/חוק הכנסת_structure_content.json
      - type: split
        source: ../takanon/extraction/חוק משכן הכנסת, רחבתו ומשמר הכנסת_structure_content.json
      - type: split
        source: ../takanon/extraction/חוק-יסוד__הכנסת_structure_content.json
      - type: split
        source: ../takanon/extraction/חוק_חסינות_חברי_הכנסת,_זכויותיהם_וחובותיהם_structure_content.json
      - type: split
        source: ../takanon/extraction/חוק_לציון_מידע_בדבר_השפעת_חקיקה_על_זכויות_הילד_structure_content.json
      - type: split
        source: ../takanon/extraction/חוק_רציפות_הדיון_בהצעות_חוק_structure_content.json
      - type: split
        source: ../takanon/extraction/תקנון הכנסת_structure_content.json
      - type: split
        source: ../takanon/extraction/חוק הפרשנות_structure_content.json

  - slug: takanon__ethics_decisions
    name: "החלטות ועדת אתיקה בדבר כללי אתיקה לחברי הכנסת"
    sources:
      - type: google-spreadsheet
        source: https://docs.google.com/spreadsheets/d/1fEgiCLNMQQZqBgQFlkABXgke8I2kI1i1XUvj8Yba9Ow/edit?gid=328434674#gid=328434674
