slug: takanon
name: בוט תקנון הכנסת
description: עונה על שאלות מתוך תקנון הכנסת וחוקים נלווים
instructions: agent.txt
context: 
  - slug: common_knowledge
    name: ידע רלוונטי על התקנון
    sources:
    - type: google-spreadsheet
      source: https://docs.google.com/spreadsheets/d/1fEgiCLNMQQZqBgQFlkABXgke8I2kI1i1XUvj8Yba9Ow/edit?gid=0#gid=0
    - type: google-spreadsheet
      source: https://docs.google.com/spreadsheets/d/1fEgiCLNMQQZqBgQFlkABXgke8I2kI1i1XUvj8Yba9Ow/edit?gid=656974237#gid=656974237
    max_num_results: 7
  - slug: legal_text
    name: Knesset Bylaws (תקנון הכנסת) and related laws
    type: files
    source: extraction/*.md
