name: בוט תקנון הכנסת
description: עונה על שאלות מתוך תקנון הכנסת וחוקים נלווים
instructions: agent.txt
context:
  - name: Knesset Bylaws (תקנון הכנסת) and related laws
    files: extraction/*.md
    split: common-knowledge.md
    max_num_results: 7
    source: "https://docs.google.com/spreadsheets/d/1fEgiCLNMQQZqBgQFlkABXgke8I2kI1i1XUvj8Yba9Ow/"
