name: בוט נתונים תקציביים
description: עונה על שאלות בנושאי תקציב המדינה, הכנסות המדינה, התקשרויות ותמיכות תקציביות
instructions: agent.txt
tools:
  - code-interpreter
  - budgetkey
context:
  - name: ידע רלוונטי על התקציב
    split: true
    source: common-knowledge.md
    max_num_results: 7
