version: "1.0.0"
name: "Test Sync Configuration"
description: "Simple test configuration for verifying sync orchestration"

# Global settings
default_versioning_strategy: "hash"
default_fetch_strategy: "direct"

# Storage configuration
cache_directory: "./cache"
embedding_cache_path: "./cache/embeddings.sqlite"
version_cache_path: "./cache/versions.json"

# Processing configuration
max_concurrent_sources: 2
timeout_per_source: 60

# Logging configuration
log_level: "INFO"
log_file: "./logs/sync.log"

# Content sources
sources:
  # Local HTML file for testing
  - id: "test-local-html"
    name: "Test Local HTML"
    description: "Local HTML file for testing sync orchestration"
    type: "html"
    html_config:
      url: "file://specs/takanon/agent.txt"
      selector: "body"
      encoding: "utf-8"
      timeout: 30
      retry_attempts: 2
    versioning_strategy: "hash"
    fetch_strategy: "direct"
    enabled: true
    priority: 1
    tags: ["test", "local", "html"]
    use_document_parser: true

  # Another local file for testing
  - id: "test-config-html"
    name: "Test Config HTML"
    description: "Another local file for testing"
    type: "html"
    html_config:
      url: "file://specs/takanon/config.yaml"
      selector: "body"
      encoding: "utf-8"
      timeout: 30
      retry_attempts: 2
    versioning_strategy: "hash"
    fetch_strategy: "direct"
    enabled: true
    priority: 2
    tags: ["test", "local", "yaml"]
    use_document_parser: true 