# This is a basic workflow to help you get started with Actions

name: Scrape PDFs

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements-pdf-scraping.txt
          pip install -e .
          # Install tesseract && Hebrew language pack:
          sudo apt-get install tesseract-ocr
          sudo apt-get install tesseract-ocr-heb
      - name: scrape
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          OPENAI_API_KEY_PRODUCTION: ${{ secrets.OPENAI_API_KEY }}
        run: |
          botnim fetch-and-process all all pdf
      - name: set git user
        run: |
          git config --global user.email "adam.kariv@gmail.com"
          git config --global user.name "Adam Kariv"
      - name: commit changes
        run: |
          git add specs
          git commit -m "New Scraped PDFs"
          git push